- menu_name: "Quick Links"

- name: "Contact Us"
  url: "/contact/"
  title: "Contact Us"

- menu_name: "Quick Links"

- name: "IITH Website"
  url: "https://iith.ac.in/"
  title: "IITH Website"

- name: "Intranet"
  url: "https://intranet.iith.ac.in/"
  title: "Intranet"

- name: "AIMS portal"
  url: "https://aims.iith.ac.in/aims/"
  title: "AIMS portal"

# - name: "RSS"
#   url: "/feed.xml"
#   title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"

# - name: "sitemap.xml"
#   url: "/sitemap.xml"
#   title: "Sitemap for Google Webmaster Tools"
